### PR TITLE
fix(index): Clarify title description question

### LINKED ISSUE #1: Add example to clarify instructions
The instruction "Write a short, imperative tense description of your change" can be unclear for non-native English speakers. This could be clarified by adding an example. "E.g. Fix formatting for challenge X".

Also, a question: This is a CLI right? Then it would break my git editor setup?

### PR DESCRIPTION
**Pull request by erictleung**
Closes #1

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -50,13 +50,13 @@ module.exports = {
         type: 'input',
         name: 'subject',
         message: dedent`
-          Write a short, imperative tense description of the change:
+          Write a short, imperative tense description of the change\n  E.g. Fix format in for loop challenge:
```
Comment (BerkeleyTrue) [inline index.js]: example should include the type. Otherwise we end up with `fix: Fix thing`

Comment (erictleung) [reply index.js]: Can you elaborate on "including the type"? I thought type was asked for [in the lines above](https://github.com/freeCodeCamp/cz-freecodecamp/pull/10/files#diff-168726dbe96b3ce427e7fedce31bb0bcL40), unless I'm misunderstanding your comment.

Comment (BerkeleyTrue) [reply index.js]: Yes, type is asked for above, this is feat, fix, chore, etc.
subject should be a imperative description of the change. This should not include the `type` or scope already recorded above.

You example includes the type in the subject. So we end up with `fix: Fix format in for loop challenge` which makes the second fix redundant.

A better example for a subject: `changed loop challenge format`. With type fix we get `fix: changed loop challenge format` as the end result
